services:
  - type: web
    name: rv-music-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FB_CLIENT_ID
        sync: false
      - key: FB_CLIENT_SECRET
        sync: false
      - key: TWITTER_CONSUMER_KEY
        sync: false
      - key: TWITTER_CONSUMER_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
